### ISSUE TITLE
Let users have usernames

### ISSUE THREAD

**Issue by arhoads** [fashion-check-me/CS397-Project#3]
Users need usernames so we can display it on the outfit page to attribute the creator. Displaying their email is no fun.

**Comment by jmhertlein** [comment]
I've made the changes to the database and added a field so that the username is set when the user signs up. 

Now we just need to make the changes in all the views so that wherever we were using @user.email, we now user @user.username (where it makes sense to do so, of course).

**Comment by jmhertlein** [comment]
I still need to make the error pretty when you try to pick a duplicate username, atm it just shows you the error from the database rejecting the transaction due to a uniqueness constraint violation.
