### ISSUE TITLE
Spring Semester Ideas

### ISSUE THREAD

**Issue by jmhertlein** [fashion-check-me/CS397-Project#7]
Here's some things i thought of that we could add to the website:

* Let people have display names / user names, instead of just email addresses
* Add a moderation queue for posts, to check for content
* Add a form to submit DMCA takedown requests on copyrighted images, to satisfy the "due care" clause of being a "Safe Harbor" (to help us not get sued)
* Add a comments system
* Clean up the UI for tags
* "mobile device support" - Make the site's design respond to the size of your screen (bootstrap does this mostly for us, but we/kelsey need to make some tweaks as we discovered at the end of last semester).
* Improve the search algorithm to allow personalized results (based on previous likes and dislikes)

I don't know how much morales wants us to do for it to qualify as being "enough work". This is certainly enough work to keep us going though, in my opinion.

Post additional ideas if you have them, it's always better to have to cut down on work than have to scramble to come up with more.

**Comment by klmaricic** [comment]
Some other suggestions:

   - Instead if the moderation queue, maybe just have a report button that
   users can use to report inappropriate pictures
   - Improve the tags so that the color/pattern is associated with the
   article of clothing. So instead of having two separate tags of "red" and
   "skirt, have a "skirt" tag that has a sub tag of "red", or something like
   that.

**Comment by jrl2n4123** [comment]
Not sure how much work this would be in the current scheme, but it would be nice to have a page for each user that shows their contributions and comments, and an emailing system you could opt into to get updates when a user contributes something.

**Comment by jmhertlein** [comment]
That's a good idea. It doesn't conflict with anything we've already done, so let's tack that on the to-do list.

**Comment by jmhertlein** [comment]
I'm going to make the bit about emailing people when their subscribed users upload images a 'stretch goal'. It's not particularly difficult or anything, it's just not something I've actually done before and keeping a list of subscribed users might require some changes in the model that could be non-trivial.
